"""gallery.py — generates index.html FROM register.json + the mockup files that
actually exist (status derived from reality, never hand-set), so the gallery can't
drift. Run: python3 gallery.py  → ../index.html (GENERATED). Honors the
self-maintenance convention: re-run after producing/addressing a mockup."""
import os, json, html as _h


def _esc(s):
    return _h.escape(str(s))


def render_gallery(register: dict, existing: set) -> str:
    produced = {}
    for p in register.get("produced", {}).get("wave1", []):
        if p.get("file") in existing:
            produced.setdefault(p["view"], []).append(p)
    areas = register.get("areas", {})
    views = register.get("views", [])
    grounded = sum(1 for v in views if v["id"] in produced)

    out = ['<!doctype html><html lang="en"><head><meta charset="utf-8"/>',
           '<meta name="viewport" content="width=device-width,initial-scale=1"/>',
           '<title>The Company — design corpus</title>',
           '<link rel="stylesheet" href="design-system.css">',
           '<style>',
           'body{padding:0;overflow:auto}.wrap{max-width:1200px;margin:0 auto;padding:32px 26px 70px}',
           "h1{font-family:'Bricolage Grotesque';font-weight:800;font-size:28px;letter-spacing:-.5px}h1 em{font-style:normal;color:var(--acc)}",
           '.sub{color:var(--tx-2);font-size:13px;margin:6px 0 8px;max-width:760px;line-height:1.55}',
           '.gen{font-family:"IBM Plex Mono";font-size:10px;color:var(--tx-3);margin-bottom:24px}',
           '.area{margin-top:30px}.area h2{font-family:"Bricolage Grotesque";font-weight:700;font-size:15px;border-bottom:1px solid var(--line);padding-bottom:8px}',
           '.area h2 .t{font-family:"IBM Plex Mono";font-size:10px;color:var(--tx-3);font-weight:400}',
           '.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(244px,1fr));gap:13px;margin-top:14px}',
           '.card{background:var(--s1);border:1px solid var(--line);border-radius:var(--r-lg);overflow:hidden;text-decoration:none;color:inherit;display:flex;flex-direction:column}',
           '.card.g{border-color:var(--acc-dim)}.thumb{aspect-ratio:16/10;background:var(--s0);border-bottom:1px solid var(--line);display:grid;place-items:center;overflow:hidden}',
           '.thumb img{width:100%;height:100%;object-fit:cover}.thumb .ph{font-family:"IBM Plex Mono";font-size:11px;color:var(--tx-3)}',
           '.meta{padding:10px 11px}.meta .t{font-size:12.5px;font-weight:500;line-height:1.3}.meta .id{font-family:"IBM Plex Mono";font-size:10px;color:var(--tx-3)}',
           '.row{display:flex;gap:5px;margin-top:8px;flex-wrap:wrap;align-items:center}',
           '.b{font-family:"IBM Plex Mono";font-size:9px;text-transform:uppercase;letter-spacing:.5px;padding:2px 6px;border-radius:4px;border:1px solid var(--line)}',
           '.b.mobile{color:var(--acc)}.b.desktop{color:var(--cache)}.b.responsive{color:var(--kind-present)}.b.tablet{color:var(--kind-model)}',
           '.st{margin-left:auto;font-family:"IBM Plex Mono";font-size:9px;text-transform:uppercase;letter-spacing:.5px;padding:2px 7px;border-radius:99px}',
           '.st.grounded{color:var(--acc);border:1px solid var(--acc-dim);background:var(--acc-glow)}.st.planned{color:var(--tx-3);border:1px solid var(--line)}.st.req{color:var(--await);border:1px solid var(--await)}',
           '.reps{font-family:"IBM Plex Mono";font-size:9px;color:var(--tx-3);margin-top:7px}',
           '</style></head><body><div class="wrap">',
           '<h1>the&nbsp;<em>company</em> — design corpus</h1>',
           '<div class="sub">Every view of the operating surface, on one shared design system, grounded in the real feature inventory. '
           'Cards link the live, resizable mockups. Status is derived from which files exist — this gallery is generated by '
           '<span style="font-family:\'IBM Plex Mono\'">_system/gallery.py</span> and cannot drift.</div>',
           f'<div class="gen">GENERATED · {grounded} grounded · {len(views)} views · {len(areas)} areas · run _system/gallery.py to refresh</div>']

    for a, aname in areas.items():
        avs = [v for v in views if v.get("area") == a]
        if not avs:
            continue
        g = sum(1 for v in avs if v["id"] in produced)
        out.append(f'<div class="area"><h2>{_esc(a)} · {_esc(aname)} <span class="t">{g}/{len(avs)} grounded</span></h2><div class="grid">')
        for v in avs:
            prods = produced.get(v["id"], [])
            is_g = bool(prods)
            status = "grounded" if is_g else ("req" if v.get("build_required") else "planned")
            slab = {"grounded": "grounded ✓", "req": "build-required", "planned": "planned"}[status]
            thumb = prods[0]["thumb"] if is_g and prods[0].get("thumb") in existing else None
            href = prods[0]["file"] if is_g else None
            tag, attrs = ("a", f' href="{_esc(href)}"') if href else ("div", "")
            thumb_html = f'<img src="{_esc(thumb)}">' if thumb else f'<span class="ph">{_esc(slab)}</span>'
            plats = "".join(f'<span class="b {p}">{_esc(p)}</span>' for p in v.get("platforms", []))
            reps = ", ".join(v.get("represents", []))
            out.append(
                f'<{tag} class="card{" g" if is_g else ""}"{attrs}>'
                f'<div class="thumb">{thumb_html}</div>'
                f'<div class="meta"><div class="t">{_esc(v.get("title",""))}</div><div class="id">{_esc(v["id"])}</div>'
                f'<div class="row">{plats}<span class="st {status}">{slab}</span></div>'
                f'{f"<div class=reps>{_esc(reps)}</div>" if reps else ""}</div></{tag}>')
        out.append('</div></div>')
    out.append('</div></body></html>')
    return "\n".join(out)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    design = os.path.dirname(here)
    register = json.load(open(os.path.join(design, "register.json"), encoding="utf-8"))
    mockdir = os.path.join(design, "mockups")
    existing = {f"mockups/{fn}" for fn in os.listdir(mockdir)} if os.path.isdir(mockdir) else set()
    html = render_gallery(register, existing)
    out = os.path.join(design, "index.html")
    open(out, "w", encoding="utf-8").write(html)
    print(f"gallery -> {out} ({len(html)} chars)")


if __name__ == "__main__":
    main()
