"""runtime/cc_images.py — IMAGES as first-class addressed fabric artifacts.

An image is its OWN typed record (image://<id>) carrying the binary's address + format metadata —
NOT a board item (the board's FRONTMATTER_KEYS is a closed schema; stuffing blob/mime into it would
pollute every board row). The binary bytes live in the content-addressed BLOB store (blob://b2:<hash>,
store.put_blob/get_blob); the image record points at them. This is the same separation decision:// uses
(a metadata row + the content it references).

What this gives — all by REUSE, no parallel machinery:
  • STORE/SAVE  → save_image(store, bytes, mime, …) → put_blob + an image://<id> record.
  • READ        → get_image(id) (the record) · image_bytes(store, id) (the bytes) · the /api/image route serves them.
  • ATTACH (hierarchical, into channels) → cc_attachments `images` type targets image://<id> (channel → [images]).
  • COMMENT     → a board item linked `commented_on` → image://<id> (the board's polymorphic typed edges).
  • LINK/REFERENCE other files → board `references` edges between image://<id> ↔ image:// ↔ any address.
  • GENERATE-INTO → an agent writes generated bytes → save_image (same path as an upload).

Storage mirrors cc_board exactly: id-keyed FLAT at channel-memory/images/<id>.md (YAML frontmatter = the
structured row, markdown body = the alt/description), atomic+fsync write, the canonical frontmatter parser.
image://<id> resolves through the ONE resolve_address seam (runtime/cognition.py), fail-loud on a missing id
(never the blob/vec silent-empty).
"""
from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone
from pathlib import Path

import yaml

from lifters.frontmatter import _extract as _fm_extract
from store.fs_store import _atomic_write_fsync

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES_DIR = os.path.join(REPO, "channel-memory", "images")

# The structured row persisted as frontmatter; `body` (the alt-text/description) is the markdown after it.
FRONTMATTER_KEYS = ("id", "address", "blob", "mime", "name", "w", "h",
                    "channel", "source", "author_session", "created", "links")

# the image MIME types we accept (fail-loud on anything else — never silently store a mystery blob as an image)
_MIME_EXT = {
    "image/png": "png", "image/jpeg": "jpg", "image/webp": "webp",
    "image/gif": "gif", "image/svg+xml": "svg", "image/avif": "avif",
}


class ImageError(RuntimeError):
    """An image op could not run — raised TEACHING-loud (never a silent no-op). Mirrors cc_board.BoardError."""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id() -> str:
    return "img-" + uuid.uuid4().hex[:8]


def _path(iid: str) -> str:
    return os.path.join(IMAGES_DIR, f"{iid}.md")


def _render(record: dict) -> str:
    fm = {k: record[k] for k in FRONTMATTER_KEYS if k in record}
    body = record.get("body", "") or ""
    return "---\n" + yaml.safe_dump(fm, sort_keys=False, allow_unicode=True) + "---\n" + body + "\n"


def _split_frontmatter(text: str) -> tuple[dict, str]:
    meta = _fm_extract(text) or {}
    body = ""
    s = text.lstrip("\n")
    if s.startswith("---"):
        rest = s[3:]
        idx = rest.find("\n---")
        if idx != -1:
            after = rest[idx + 4:]
            nl = after.find("\n")
            body = after[nl + 1:] if nl != -1 else ""
    return meta, body.strip("\n")


def _sniff_mime(data: bytes, declared: str = "") -> str:
    """Trust-but-verify: a declared mime must match the magic bytes (no mislabeled blobs). If none declared,
    sniff from the magic bytes. Fail-loud on an unrecognised/declared-mismatched type."""
    sniffed = ""
    if data[:8].startswith(b"\x89PNG\r\n\x1a\n"):
        sniffed = "image/png"
    elif data[:3] == b"\xff\xd8\xff":
        sniffed = "image/jpeg"
    elif data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        sniffed = "image/webp"
    elif data[:6] in (b"GIF87a", b"GIF89a"):
        sniffed = "image/gif"
    elif b"<svg" in data[:512].lower() or data[:5] == b"<?xml":
        sniffed = "image/svg+xml"
    if declared:
        if sniffed and declared != sniffed:
            raise ImageError(
                f"declared mime {declared!r} does not match the actual bytes ({sniffed!r}) — "
                f"refusing to store a mislabeled image. Pass the true mime or omit it.")
        if declared not in _MIME_EXT:
            raise ImageError(f"unsupported mime {declared!r} — valid: {sorted(_MIME_EXT)}.")
        return declared
    if not sniffed:
        raise ImageError(
            "could not recognise the image type from its bytes (not PNG/JPEG/WebP/GIF/SVG) — "
            "pass an explicit `mime` if this is a supported format, else it is not an image.")
    return sniffed


# ── the ops ─────────────────────────────────────────────────────────────────────────────────────────────
def save_image(store, data: bytes, *, mime: str = "", name: str = "", channel: str = "",
               author_session: str, source: str = "claude_code", alt: str = "",
               w: int = 0, h: int = 0, links=None) -> dict:
    """STORE an image: the bytes → the content-addressed blob store (write-once, dedup), + an image://<id>
    record carrying {blob, mime, name, w, h, channel, provenance}. This is the SAME path for an uploaded
    image and a GENERATED one (an agent's bytes). Returns the image record. Fail-loud on a non-image."""
    if not isinstance(data, (bytes, bytearray)):
        raise ImageError(f"save_image expects image bytes, got {type(data).__name__}.")
    if not author_session:
        raise ImageError("save_image needs `author_session` (provenance — who/what created this image).")
    data = bytes(data)
    mime = _sniff_mime(data, mime)
    blob = store.put_blob(data)                         # content-addressed: identical bytes dedup to one blob
    os.makedirs(IMAGES_DIR, exist_ok=True)
    iid = _new_id()
    while os.path.exists(_path(iid)):
        iid = _new_id()
    record = {
        "id": iid,
        "address": f"image://{iid}",
        "blob": blob,
        "mime": mime,
        "name": name or iid,
        "w": int(w), "h": int(h),
        "channel": channel,
        "source": source,
        "author_session": author_session,
        "created": _now(),
        "links": list(links or []),
        "body": alt,
    }
    _atomic_write_fsync(Path(_path(iid)), _render(record))
    return record


def get_image(iid: str) -> dict:
    """READ one image record by id (image://<id> resolves here). Fail-loud if missing/unparseable."""
    iid = iid.split("://")[-1]
    p = _path(iid)
    if not os.path.exists(p):
        raise ImageError(f"no image {iid!r} at {p} — get on a missing image fails loud (never a silent empty).")
    with open(p, encoding="utf-8") as f:
        meta, body = _split_frontmatter(f.read())
    if not meta.get("id"):
        raise ImageError(f"image {iid!r} at {p} has no parseable frontmatter — malformed record, fail loud.")
    rec = dict(meta)
    rec["body"] = body
    rec.setdefault("links", [])
    return rec


def image_bytes(store, iid: str) -> tuple[bytes, str]:
    """The actual image BYTES + its mime (resolve the record → its blob → the bytes). For the serve route."""
    rec = get_image(iid)
    return store.get_blob(rec["blob"]), rec.get("mime", "application/octet-stream")


def list_images(channel: str | None = None) -> list[dict]:
    """List image records, newest-first; optional `channel` filter. Empty is HONEST (never fabricated)."""
    if not os.path.isdir(IMAGES_DIR):
        return []
    out = []
    for fn in os.listdir(IMAGES_DIR):
        if not fn.endswith(".md"):
            continue
        try:
            rec = get_image(fn[:-3])
        except ImageError:
            continue
        if channel and rec.get("channel") != channel:
            continue
        out.append(rec)
    out.sort(key=lambda r: r.get("created", ""), reverse=True)
    return out
