"""runtime/ci_scaffold.py — S-R9.1 CI SCAFFOLDER (CC-30): generate a CI workflow that runs a
Claude-Code task, from a routine's prompt + cadence. The RUN happens on the CI provider's runner
(GitHub Actions / GitLab CI) — off-machine, NOT Company-buildable; what IS buildable is the
SCAFFOLDING: the workflow file. Templates are the canonical ones from ui-contract/resources/ci.md.

GENERATES, NEVER INSTALLS. Returns the workflow text + the canonical target path for the operator to
drop into their repo; it does NOT install the GitHub app, set secrets, push, or commit to any repo
(those are off-machine operator steps). A routine's `cadence` ('OnCalendar=...'/'every:<s>') maps to
a GitHub `schedule: cron` where expressible (a daily 'OnCalendar=*-*-* HH:MM:SS' → '0 HH * * *' style).
"""
from __future__ import annotations

import re

from runtime.routines import Routine, routine_registry


def _cadence_to_cron(cadence: str) -> "str | None":
    """Best-effort map a routine cadence → a 5-field cron for GitHub `schedule:`. Returns None if
    not cleanly expressible (the workflow is then on-demand / @claude-triggered, not scheduled)."""
    c = (cadence or "").strip()
    m = re.match(r"OnCalendar=\*-\*-\* (\d{1,2}):(\d{2}):\d{2}$", c)
    if m:
        return f"{int(m.group(2))} {int(m.group(1))} * * *"     # daily at HH:MM (UTC on the runner)
    m = re.match(r"every:(\d+)$", c)
    if m and int(m.group(1)) % 3600 == 0 and int(m.group(1)) // 3600 >= 1:
        h = int(m.group(1)) // 3600
        return f"0 */{h} * * *" if h < 24 else "0 0 * * *"      # every N hours (N<24) else daily
    return None


def github_workflow(name: str, prompt: str, *, cron: "str | None" = None, model: str = "opus") -> str:
    """A .github/workflows/<name>.yml running claude-code-action — scheduled (cron) or on @claude."""
    trigger = (f"  schedule:\n    - cron: \"{cron}\"\n" if cron
               else "  issue_comment:\n    types: [created]\n")
    safe = prompt.replace('"', "'")
    return f"""# .github/workflows/{name}.yml — GENERATED by the Company CI scaffolder (S-R9.1 / CC-30).
# Install: add the ANTHROPIC_API_KEY repo secret + `/install-github-app` (off-machine, operator step).
name: {name}
on:
{trigger}jobs:
  {name.replace('-', '_')}:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          prompt: "{safe}"
          claude_args: "--model {model}"
"""


def gitlab_job(prompt: str, *, model: str = "opus") -> str:
    """A .gitlab-ci.yml `claude` job running headless `claude -p` (Claude API + mcp__gitlab)."""
    safe = prompt.replace('"', "'")
    return f"""# .gitlab-ci.yml (append) — GENERATED by the Company CI scaffolder (S-R9.1 / CC-30).
# ANTHROPIC_API_KEY must be a masked CI/CD variable (off-machine, operator step).
claude:
  stage: ai
  image: node:24-alpine3.21
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script:
    - apk add --no-cache git curl bash
    - curl -fsSL https://claude.ai/install.sh | bash
  script:
    - >
      claude -p "{safe}"
      --model {model}
      --permission-mode acceptEdits
      --allowedTools "Bash Read Edit Write mcp__gitlab"
"""


def scaffold_from_routine(routine_or_id, *, provider: str = "github") -> dict:
    """Generate a CI workflow from a routine. Returns {provider, target_path, workflow, note}."""
    routine = routine_or_id if isinstance(routine_or_id, Routine) else routine_registry()[routine_or_id]
    if provider == "github":
        cron = _cadence_to_cron(routine.cadence) if routine.cadence else None
        name = f"claude-{routine.id}".replace("_", "-")
        wf = github_workflow(name, routine.prompt, cron=cron, model=routine.model or "opus")
        return {"provider": "github", "target_path": f".github/workflows/{name}.yml", "workflow": wf,
                "scheduled": bool(cron),
                "note": "GENERATED — drop into the target repo, add the ANTHROPIC_API_KEY secret + "
                        "install the GitHub app (off-machine operator steps). The run happens on "
                        "GitHub's runner, not the Company."}
    if provider == "gitlab":
        wf = gitlab_job(routine.prompt, model=routine.model or "opus")
        return {"provider": "gitlab", "target_path": ".gitlab-ci.yml (append the `claude` job)",
                "workflow": wf, "scheduled": False,
                "note": "GENERATED — append to .gitlab-ci.yml, add a masked ANTHROPIC_API_KEY CI/CD "
                        "variable (off-machine). The run happens on a GitLab runner, not the Company."}
    raise ValueError(f"unknown provider {provider!r} — 'github' or 'gitlab'.")


if __name__ == "__main__":
    import json, sys
    rid = sys.argv[1] if len(sys.argv) > 1 else "self_status"
    prov = sys.argv[2] if len(sys.argv) > 2 else "github"
    out = scaffold_from_routine(rid, provider=prov)
    print(out["workflow"])
    print("# target:", out["target_path"], "| scheduled:", out.get("scheduled"))
