"""types/agent.py — the Agent universal type (④ L3 · SOUND cloud type landed as a file).
Its `id` MUST equal the file stem ('agent'). See types/AGENTS.md + runtime/type_registry.py.
data_schema/component_spec/status_values recovered from cvi_mine (READ-ONLY); generated artifacts
are REGENERATED by generate_all, never migrated."""

TYPE = {   'data_schema': {   'properties': {   'agent_name': {'type': 'string'},
                                         'capabilities': {'type': 'array'},
                                         'mode': {'type': 'string'},
                                         'model': {'type': 'string'},
                                         'provider': {'type': 'string'},
                                         'status': {   'enum': [   'active',
                                                                   'idle',
                                                                   'processing',
                                                                   'error'],
                                                       'type': 'string'}},
                       'type': 'object'},
    'desc': 'Agent — landed from cvi_mine universal_types (SOUND); component_spec→faces.board, '
            'status_values→states (law 11).',
    'faces': {   'address': {'template': 'vi.{user}.agent.{id}'},
                 'board': {   'color': '#6366f1',
                              'icon': 'bot',
                              'renderer': 'AgentCard',
                              'status_values': [   'active',
                                                   'idle',
                                                   'processing',
                                                   'error',
                                                   'provisioning']},
                 'tool': {'verbs': ['create', 'list', 'get', 'update']}},
    'id': 'agent',
    'initial': 'active',
    'label': 'Agent',
    'provenance': 'cloud:universal_types (SOUND — non-trivial data_schema; landed as a file, '
                  'artifacts regenerated not migrated)',
    'states': ['active', 'idle', 'processing', 'error', 'provisioning'],
    'transitions': {   'active': ['idle', 'processing', 'error', 'provisioning'],
                       'error': ['provisioning'],
                       'idle': ['processing', 'error', 'provisioning'],
                       'processing': ['error', 'provisioning'],
                       'provisioning': []},
    'version': 1}
