"""types/cognitive_guide.py — the Cognitive Guide universal type (④ L3 · SOUND cloud type landed as a file).
Its `id` MUST equal the file stem ('cognitive_guide'). See types/AGENTS.md + runtime/type_registry.py.
data_schema/component_spec/status_values recovered from cvi_mine (READ-ONLY); generated artifacts
are REGENERATED by generate_all, never migrated."""

TYPE = {   'data_schema': {   'properties': {   'guide_content': {'type': 'string'},
                                         'priority': {'type': 'integer'},
                                         'requires_decision': {'type': 'boolean'},
                                         'seen_by': {'type': 'array'},
                                         'target_view': {'type': 'string'}},
                       'type': 'object'},
    'desc': 'Cognitive Guide — landed from cvi_mine universal_types (SOUND); '
            'component_spec→faces.board, status_values→states (law 11).',
    'faces': {   'address': {'template': 'vi.{user}.cognitive_guide.{id}'},
                 'board': {   'color': '#D4AF37',
                              'icon': 'compass',
                              'renderer': 'GuideCard',
                              'status_values': ['unseen', 'seen', 'dismissed', 'acted_on']}},
    'id': 'cognitive_guide',
    'initial': 'unseen',
    'label': 'Cognitive Guide',
    'provenance': 'cloud:universal_types (SOUND — non-trivial data_schema; landed as a file, '
                  'artifacts regenerated not migrated)',
    'states': ['unseen', 'seen', 'dismissed', 'acted_on'],
    'transitions': {   'acted_on': [],
                       'dismissed': ['acted_on'],
                       'seen': ['dismissed', 'acted_on'],
                       'unseen': ['seen', 'dismissed', 'acted_on']},
    'version': 1}
