"""types/deployment.py — the Deployment universal type (④ L3 · SOUND cloud type landed as a file).
Its `id` MUST equal the file stem ('deployment'). See types/AGENTS.md + runtime/type_registry.py.
data_schema/component_spec/status_values recovered from cvi_mine (READ-ONLY); generated artifacts
are REGENERATED by generate_all, never migrated."""

TYPE = {   'data_schema': {   'properties': {   'assistant_count': {'type': 'integer'},
                                         'deployment_name': {'type': 'string'},
                                         'graph_count': {'type': 'integer'},
                                         'platform': {'type': 'string'},
                                         'status': {'type': 'string'}},
                       'type': 'object'},
    'desc': 'Deployment — landed from cvi_mine universal_types (SOUND); '
            'component_spec→faces.board, status_values→states (law 11).',
    'faces': {   'address': {'template': 'vi.{user}.deployment.{id}'},
                 'board': {   'color': '#06b6d4',
                              'icon': 'cloud',
                              'renderer': 'DeploymentCard',
                              'status_values': ['active', 'deploying', 'stopped', 'error']},
                 'tool': {'verbs': ['create', 'list', 'get', 'update']}},
    'id': 'deployment',
    'initial': 'active',
    'label': 'Deployment',
    'provenance': 'cloud:universal_types (SOUND — non-trivial data_schema; landed as a file, '
                  'artifacts regenerated not migrated)',
    'states': ['active', 'deploying', 'stopped', 'error'],
    'transitions': {   'active': ['deploying', 'stopped', 'error'],
                       'deploying': ['stopped', 'error'],
                       'error': [],
                       'stopped': ['error']},
    'version': 1}
