"""types/design.py — the Design universal type (④ L3 · SOUND cloud type landed as a file).
Its `id` MUST equal the file stem ('design'). See types/AGENTS.md + runtime/type_registry.py.
data_schema/component_spec/status_values recovered from cvi_mine (READ-ONLY); generated artifacts
are REGENERATED by generate_all, never migrated."""

TYPE = {   'data_schema': {   'properties': {   'description': {'type': 'string'},
                                         'title': {'type': 'string'}},
                       'type': 'object'},
    'desc': 'Design — landed from cvi_mine universal_types (SOUND); component_spec→faces.board, '
            'status_values→states (law 11).',
    'faces': {   'address': {'template': 'vi.{user}.design.{id}'},
                 'board': {   'color': '#06b6d4',
                              'icon': 'palette',
                              'renderer': 'DesignCard',
                              'status_values': ['draft', 'approved']},
                 'tool': {'verbs': ['create', 'list', 'get', 'update']}},
    'id': 'design',
    'initial': 'draft',
    'label': 'Design',
    'provenance': 'cloud:universal_types (SOUND — non-trivial data_schema; landed as a file, '
                  'artifacts regenerated not migrated)',
    'states': ['draft', 'approved'],
    'transitions': {'approved': [], 'draft': ['approved']},
    'version': 1}
