"""types/issue.py — the Issue universal type (④ L3 · SOUND cloud type landed as a file).
Its `id` MUST equal the file stem ('issue'). See types/AGENTS.md + runtime/type_registry.py.
data_schema/component_spec/status_values recovered from cvi_mine (READ-ONLY); generated artifacts
are REGENERATED by generate_all, never migrated."""

TYPE = {   'data_schema': {   'properties': {   'description': {'type': 'string'},
                                         'priority': {'type': 'string'},
                                         'status': {'type': 'string'},
                                         'title': {'type': 'string'}},
                       'type': 'object'},
    'desc': 'Issue — landed from cvi_mine universal_types (SOUND); component_spec→faces.board, '
            'status_values→states (law 11).',
    'faces': {   'address': {'template': 'vi.{user}.issue.{id}'},
                 'board': {   'color': '#ef4444',
                              'icon': 'bug',
                              'renderer': 'IssueCard',
                              'status_values': ['open', 'resolved', 'closed']},
                 'tool': {'verbs': ['create', 'list', 'get', 'update']}},
    'id': 'issue',
    'initial': 'open',
    'label': 'Issue',
    'provenance': 'cloud:universal_types (SOUND — non-trivial data_schema; landed as a file, '
                  'artifacts regenerated not migrated)',
    'states': ['open', 'resolved', 'closed'],
    'transitions': {'closed': [], 'open': ['resolved', 'closed'], 'resolved': ['closed']},
    'version': 1}
