"""types/model_provider.py — the Model Provider universal type (④ L3 · SOUND cloud type landed as a file).
Its `id` MUST equal the file stem ('model_provider'). See types/AGENTS.md + runtime/type_registry.py.
data_schema/component_spec/status_values recovered from cvi_mine (READ-ONLY); generated artifacts
are REGENERATED by generate_all, never migrated."""

TYPE = {   'data_schema': {   'properties': {   'display_name': {'type': 'string'},
                                         'model_count': {'type': 'integer'},
                                         'provider_name': {'type': 'string'},
                                         'supports_thinking': {'type': 'boolean'},
                                         'supports_tools': {'type': 'boolean'},
                                         'supports_vision': {'type': 'boolean'}},
                       'type': 'object'},
    'desc': 'Model Provider — landed from cvi_mine universal_types (SOUND); '
            'component_spec→faces.board, status_values→states (law 11).',
    'faces': {   'address': {'template': 'vi.{user}.model_provider.{id}'},
                 'board': {   'color': '#8b5cf6',
                              'icon': 'cpu',
                              'renderer': 'ProviderCard',
                              'status_values': ['active', 'inactive', 'deprecated']},
                 'tool': {'verbs': ['create', 'list', 'get', 'update']}},
    'id': 'model_provider',
    'initial': 'active',
    'label': 'Model Provider',
    'provenance': 'cloud:universal_types (SOUND — non-trivial data_schema; landed as a file, '
                  'artifacts regenerated not migrated)',
    'states': ['active', 'inactive', 'deprecated'],
    'transitions': {   'active': ['inactive', 'deprecated'],
                       'deprecated': [],
                       'inactive': ['deprecated']},
    'version': 1}
