"""types/proposal.py — the Proposal universal type (④ L3 · SOUND cloud type landed as a file).
Its `id` MUST equal the file stem ('proposal'). See types/AGENTS.md + runtime/type_registry.py.
data_schema/component_spec/status_values recovered from cvi_mine (READ-ONLY); generated artifacts
are REGENERATED by generate_all, never migrated."""

TYPE = {   'data_schema': {   'properties': {   'description': {'type': 'string'},
                                         'priority': {'type': 'string'},
                                         'title': {'type': 'string'}},
                       'type': 'object'},
    'desc': 'Proposal — landed from cvi_mine universal_types (SOUND); component_spec→faces.board, '
            'status_values→states (law 11).',
    'faces': {   'address': {'template': 'vi.{user}.proposal.{id}'},
                 'board': {   'color': '#8b5cf6',
                              'icon': 'lightbulb',
                              'renderer': 'ProposalCard',
                              'status_values': ['draft', 'review', 'approved', 'rejected']},
                 'tool': {'verbs': ['create', 'list', 'get', 'update']}},
    'id': 'proposal',
    'initial': 'draft',
    'label': 'Proposal',
    'provenance': 'cloud:universal_types (SOUND — non-trivial data_schema; landed as a file, '
                  'artifacts regenerated not migrated)',
    'states': ['draft', 'review', 'approved', 'rejected'],
    'transitions': {   'approved': ['rejected'],
                       'draft': ['review', 'approved', 'rejected'],
                       'rejected': [],
                       'review': ['approved', 'rejected']},
    'version': 1}
