"""types/request.py — the Request universal type (④ L3 · SOUND cloud type landed as a file).
Its `id` MUST equal the file stem ('request'). See types/AGENTS.md + runtime/type_registry.py.
data_schema/component_spec/status_values recovered from cvi_mine (READ-ONLY); generated artifacts
are REGENERATED by generate_all, never migrated."""

TYPE = {   'data_schema': {   'properties': {   'description': {'type': 'string'},
                                         'priority': {'type': 'string'},
                                         'title': {'type': 'string'}},
                       'type': 'object'},
    'desc': 'Request — landed from cvi_mine universal_types (SOUND); component_spec→faces.board, '
            'status_values→states (law 11).',
    'faces': {   'address': {'template': 'vi.{user}.request.{id}'},
                 'board': {   'color': '#f59e0b',
                              'icon': 'file-text',
                              'renderer': 'RequestCard',
                              'status_values': ['submitted', 'approved', 'declined']},
                 'tool': {'verbs': ['create', 'list', 'get', 'update']}},
    'id': 'request',
    'initial': 'submitted',
    'label': 'Request',
    'provenance': 'cloud:universal_types (SOUND — non-trivial data_schema; landed as a file, '
                  'artifacts regenerated not migrated)',
    'states': ['submitted', 'approved', 'declined'],
    'transitions': {   'approved': ['declined'],
                       'declined': [],
                       'submitted': ['approved', 'declined']},
    'version': 1}
