"""types/system_graph.py — the System Graph universal type (④ L3 · SOUND cloud type landed as a file).
Its `id` MUST equal the file stem ('system_graph'). See types/AGENTS.md + runtime/type_registry.py.
data_schema/component_spec/status_values recovered from cvi_mine (READ-ONLY); generated artifacts
are REGENERATED by generate_all, never migrated."""

TYPE = {   'data_schema': {   'properties': {   'edge_count': {'type': 'integer'},
                                         'lens': {   'enum': [   'all',
                                                                 'coordination',
                                                                 'conversation',
                                                                 'knowledge',
                                                                 'behavior'],
                                                     'type': 'string'},
                                         'project_key': {'type': 'string'},
                                         'sources': {'items': {'type': 'string'}, 'type': 'array'}},
                       'type': 'object'},
    'desc': 'System Graph — landed from cvi_mine universal_types (SOUND); '
            'component_spec→faces.board, status_values→states (law 11).',
    'faces': {   'address': {'template': 'vi.{user}.system_graph.{id}'},
                 'board': {   'color': '#6366f1',
                              'icon': 'git-branch',
                              'renderer': 'GraphView',
                              'status_values': ['draft', 'active', 'archived']},
                 'tool': {'verbs': ['create', 'list', 'get', 'update']}},
    'id': 'system_graph',
    'initial': 'draft',
    'label': 'System Graph',
    'provenance': 'cloud:universal_types (SOUND — non-trivial data_schema; landed as a file, '
                  'artifacts regenerated not migrated)',
    'states': ['draft', 'active', 'archived'],
    'transitions': {'active': ['archived'], 'archived': [], 'draft': ['active', 'archived']},
    'version': 1}
