"""modes/background.py — presence mode «background» (file-discovered MODE registry, WS0 2026-06-28).
Generated byte-for-byte from the former hardcoded MODE_REGISTRY literal; edit freely — this is now
the source. `order` sequences the order-bearing mode tuple (lower first). See runtime/modes_registry.py.
"""
MODE = {'order': 20,
 'label': 'Background',
 'directive': 'Be minimal — surface only what genuinely needs the operator; otherwise a one-line '
              'acknowledgement.',
 'resolution': {'strata': frozenset({'run', 'presentation_pref', 'howto', 'event'}),
                'howto_detail': 'terse',
                'budget': 1500},
 'consent': 'act',
 'grain': 'line',
 'shape': 'scatter-write',
 'stage': False,
 'live': ['per-turn', 'background', 'sense', 'rollup'],
 'reserve_r': 2,
 'per_role_ctx': 1500,
 'main_ctx_tokens': 40000,
 'brain_config': 'swarm-16k'}
