"""modes/decide-for-me.py — presence mode «decide-for-me» (file-discovered MODE registry, WS0 2026-06-28).
Generated byte-for-byte from the former hardcoded MODE_REGISTRY literal; edit freely — this is now
the source. `order` sequences the order-bearing mode tuple (lower first). See runtime/modes_registry.py.
"""
MODE = {'order': 60,
 'label': 'Decide for me',
 'directive': 'Act on what the governance posture lets you act on (the AUTO/reversible classes — propose a '
              'node, run the graph) rather than asking; surface the rest for the operator. The routing is '
              "deterministic (the action's posture decides), not a judgement call. You still cannot "
              'self-approve; anything that needs approval is surfaced.',
 'resolution': {'strata': None, 'howto_detail': 'full', 'budget': None},
 'consent': 'act',
 'grain': 'paragraph',
 'shape': 'linear-stream',
 'stage': True,
 'live': ['per-turn', 'background', 'rollup'],
 'reserve_r': 2,
 'per_role_ctx': 1500,
 'main_ctx_tokens': 0,
 'brain_config': 'voice-64k',
 'voice': 'on'}
