"""modes/focus.py — presence mode «focus» (file-discovered MODE registry, WS0 2026-06-28).
Generated byte-for-byte from the former hardcoded MODE_REGISTRY literal; edit freely — this is now
the source. `order` sequences the order-bearing mode tuple (lower first). See runtime/modes_registry.py.
"""
MODE = {'order': 30,
 'label': 'Focus',
 'directive': 'The operator is in deep work. Be extremely brief (one or two lines); do not elaborate '
              'unless asked.',
 'resolution': {'strata': frozenset({'run', 'chat', 'annotation', 'event'}),
                'howto_detail': 'none',
                'budget': 800},
 'subtypes': {'default': {}, 'structural': {'strata': frozenset({'run', 'event'}), 'budget': 600}},
 'consent': 'act',
 'grain': 'line',
 'shape': 'linear-stream',
 'stage': False,
 'live': ['per-turn', 'background'],
 'reserve_r': 2,
 'per_role_ctx': 1500,
 'main_ctx_tokens': 0,
 'brain_config': 'voice-64k'}
