"""modes/listening.py — presence mode «listening» (file-discovered MODE registry, WS0 2026-06-28).
Generated byte-for-byte from the former hardcoded MODE_REGISTRY literal; edit freely — this is now
the source. `order` sequences the order-bearing mode tuple (lower first). See runtime/modes_registry.py.
"""
MODE = {'order': 0,
 'label': 'Listening',
 'directive': 'Conversational and present; respond fully.',
 'resolution': {'strata': None, 'howto_detail': 'full', 'budget': None},
 'subtypes': {'general': {}, 'deep': {'budget': 8000}},
 'consent': 'offer',
 'grain': 'beat',
 'shape': 'linear-stream',
 'stage': True,
 'live': ['per-turn', 'background', 'sense', 'rollup'],
 'reserve_r': 2,
 'per_role_ctx': 1500,
 'main_ctx_tokens': 0,
 'brain_config': 'voice-64k'}
