"""modes/off.py — presence mode «off» (file-discovered MODE registry, WS0 2026-06-28).
Generated byte-for-byte from the former hardcoded MODE_REGISTRY literal; edit freely — this is now
the source. `order` sequences the order-bearing mode tuple (lower first). See runtime/modes_registry.py.
"""
MODE = {'order': 70,
 'label': 'Off',
 'directive': 'The right-hand-man is asleep — no conversation, no actions. Switch any other mode on the '
              'presence dial to wake it.',
 'resolution': {'strata': frozenset(), 'howto_detail': 'none', 'budget': 0},
 'consent': 'none',
 'grain': 'line',
 'shape': 'linear-stream',
 'stage': False,
 'live': ['per-turn'],
 'reserve_r': 2,
 'per_role_ctx': 1500,
 'main_ctx_tokens': 0,
 'brain_config': 'voice-64k'}
