"""modes/text-only.py — presence mode «text-only» (file-discovered MODE registry, WS0 2026-06-28).
Generated byte-for-byte from the former hardcoded MODE_REGISTRY literal; edit freely — this is now
the source. `order` sequences the order-bearing mode tuple (lower first). See runtime/modes_registry.py.
"""
MODE = {'order': 10,
 'label': 'Text-only',
 'directive': 'Respond in text, concisely, only to what is addressed.',
 'resolution': {'strata': None, 'howto_detail': 'full', 'budget': None},
 'consent': 'offer',
 'grain': 'paragraph',
 'shape': 'linear-stream',
 'stage': True,
 'live': ['per-turn', 'rollup'],
 'reserve_r': 2,
 'per_role_ctx': 1500,
 'main_ctx_tokens': 0,
 'brain_config': 'voice-64k',
 'voice': 'off'}
