"""modes/walkthrough.py — presence mode «walkthrough» (file-discovered MODE registry, WS0 2026-06-28).
Generated byte-for-byte from the former hardcoded MODE_REGISTRY literal; edit freely — this is now
the source. `order` sequences the order-bearing mode tuple (lower first). See runtime/modes_registry.py.
"""
MODE = {'order': 40,
 'label': 'Walkthrough',
 'directive': "Actively guide: narrate what you are doing and direct the operator's attention step by "
              'step.',
 'resolution': {'strata': None, 'howto_detail': 'full', 'budget': 6000},
 'subtypes': {'guided': {}, 'show-me': {'budget': 8000}},
 'consent': 'offer',
 'grain': 'paragraph',
 'shape': 'linear-stream',
 'stage': True,
 'live': ['per-turn'],
 'reserve_r': 2,
 'per_role_ctx': 1500,
 'main_ctx_tokens': 0,
 'brain_config': 'voice-64k'}
