"""modes/watch-and-react.py — presence mode «watch-and-react» (file-discovered MODE registry, WS0 2026-06-28).
Generated byte-for-byte from the former hardcoded MODE_REGISTRY literal; edit freely — this is now
the source. `order` sequences the order-bearing mode tuple (lower first). See runtime/modes_registry.py.
"""
MODE = {'order': 50,
 'label': 'Watch & react',
 'directive': 'Observe; comment only when relevant, and briefly.',
 'resolution': {'strata': frozenset({'run', 'presentation_pref', 'howto', 'event'}),
                'howto_detail': 'terse',
                'budget': 1500},
 'consent': 'act',
 'grain': 'line',
 'shape': 'linear-stream',
 'stage': True,
 'live': ['per-turn', 'sense'],
 'reserve_r': 2,
 'per_role_ctx': 1500,
 'main_ctx_tokens': 0,
 'brain_config': 'voice-64k'}
