// sync-gallery.mjs — the DOM-MOUNT SEAM's copy-on-build step (runs as predev + prebuild).
//
// The first-slice FACE is DNA's render module (ONE renderer, MANY sources). DNA OWNS it — it lives in
// DNA's repo (counterpart/design/ui/). The surface HOSTS it (so DNA's /api/cognition/corpus fetch is
// same-origin + fork/wildcard get stable element refs). To host without taking custody (no silent
// drift, no stale hand-copy), we COPY DNA's canonical files into public/gallery/ on every dev/build —
// fresh every time, identical in dev and prod, and FAIL LOUD if DNA's source is missing (never serve a
// silently-stale or absent module). DNA edits her source; the next dev/build picks it up. Registry-of-
// truth for the module = DNA's repo, not this copy.
import { existsSync, mkdirSync, copyFileSync, statSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const PUBLIC_GALLERY = join(HERE, '..', 'public', 'gallery')

// DNA's canonical source (env-overridable so a relocated checkout still resolves; default = the fleet path).
const DNA_UI = process.env.DNA_UI_DIR || '/home/tim/repos/counterpart/design/ui'

// the files the host needs to render the gallery face: DNA's renderer + its look.
const FILES = ['unit-view.js', 'phone.css']

const missing = FILES.filter((f) => !existsSync(join(DNA_UI, f)))
if (missing.length) {
  // FAIL LOUD (no silent fallback) — a missing DNA source means the gallery face can't be hosted; say so.
  console.error(
    `\n[sync-gallery] FAIL LOUD — DNA's render module is missing at ${DNA_UI}:\n` +
      missing.map((f) => `  - ${f}`).join('\n') +
      `\nThe gallery first-slice FACE is hosted FROM DNA's repo (she owns it).\n` +
      `Fix: ensure counterpart/design is checked out, or set DNA_UI_DIR to its ui/ path.\n`,
  )
  process.exit(1)
}

mkdirSync(PUBLIC_GALLERY, { recursive: true })
for (const f of FILES) {
  const src = join(DNA_UI, f)
  const dst = join(PUBLIC_GALLERY, f)
  copyFileSync(src, dst)
  console.log(`[sync-gallery] ${f}  (${statSync(src).size}B)  ← ${src}`)
}

// DNA's TOKEN VOCABULARY (:root --dna-space-*/--dna-radius-*/--warmpole-* etc.) lives in piece.css — but
// piece.css ALSO carries a global `*{margin:0;padding:0}` reset + a `body{display:flex;background}` rule that
// would WRECK the host surface if loaded whole. phone.css's values are token-based, so without these tokens
// every padding/radius collapses (DNA's diagnosis: .uv-chips render run-together). So we EXTRACT ONLY the
// :root token blocks into a standalone dna-tokens.css — the tokens phone.css needs, none of the dangerous
// globals. FAIL LOUD if piece.css or its :root is absent (the face's look depends on these tokens).
const PIECE = join(DNA_UI, 'piece.css')
if (!existsSync(PIECE)) {
  console.error(`\n[sync-gallery] FAIL LOUD — DNA's token source piece.css missing at ${PIECE}\n` +
    `phone.css is token-based; without :root tokens the face's spacing/radius/warmth collapse.\n`)
  process.exit(1)
}
const pieceCss = readFileSync(PIECE, 'utf8')
// :root blocks are flat var-declaration lists (no nested braces) → a non-greedy {…} match is exact.
const rootBlocks = pieceCss.match(/:root\s*\{[^}]*\}/g)
if (!rootBlocks || !rootBlocks.length) {
  console.error(`\n[sync-gallery] FAIL LOUD — no :root token block found in ${PIECE} (DNA restructured?).\n` +
    `The gallery face's tokens cannot be hosted; aborting rather than serving a token-starved render.\n`)
  process.exit(1)
}
const tokensCss =
  `/* GENERATED by scripts/sync-gallery.mjs — DNA's :root token vocabulary EXTRACTED from piece.css.\n` +
  `   ONLY the :root blocks (no piece.css global *-reset / body rule, which would wreck the host surface).\n` +
  `   phone.css is token-based; these make its spacing/radius/warmth resolve in the host. DNA owns the source. */\n` +
  rootBlocks.join('\n\n') + '\n'
writeFileSync(join(PUBLIC_GALLERY, 'dna-tokens.css'), tokensCss)
console.log(`[sync-gallery] dna-tokens.css  (${rootBlocks.length} :root block(s), ${tokensCss.length}B)  ← extracted from piece.css`)

console.log(`[sync-gallery] hosted DNA's gallery face at public/gallery/ (DNA owns the source; this is a fresh copy).`)
