"""C4 — the Resolver Protocol. See build-prep/contracts/C4.

The only thing that changes filesystem -> Supabase. `store/fs_store.py` implements it.
"""
from __future__ import annotations
from typing import Any, Protocol, runtime_checkable
from contracts.address import Provenance


@runtime_checkable
class Resolver(Protocol):
    # immutable content (cas://)
    def put_content(self, data: Any) -> str: ...
    def get_content(self, cas: str) -> Any: ...
    def exists(self, cas: str) -> bool: ...
    # mutable pointer (run://)
    def set_ref(self, logical: str, cas: str) -> None: ...
    def head(self, logical: str) -> str | None: ...
    # provenance + lineage
    def write_provenance(self, prov: Provenance) -> None: ...
    def provenance(self, address: str) -> Provenance | None: ...
    def lineage(self, address: str) -> list[str]: ...   # walk inputs back toward source
    # memo (the gate)
    def memo_get(self, sig: str) -> str | None: ...
    def memo_set(self, sig: str, cas: str) -> None: ...
